Remove scatter plot and replace a bar chart with discussed colour theme
UBC-MDS/DSCI-532_2024_5_HomeScope pull request #59
Opened 2024-04-08 23:32 UTC by carrieyanyi

2024-04-09 00:04 UTC, Aishwarya120111 requested changes
Plot is very good. I feel like it would be better if we change the title of plot
City-wise Bedroom Count Distribution or Top 5 Most Common Bedroom Counts in Homes Across Cities or Top 5 Bedroom Counts Across Cities

2024-04-09 04:49 UTC, carrieyanyi commented
Sure. @Aishwarya120111. I am thinking about changing the column names to remove the underscore in each variable when loading the dataset.

2024-04-09 22:02 UTC, iris0614 approved these changes
It looks good to me. We can discuss the x and y axes for the bar plot later.

2024-04-10 04:18 UTC, Aishwarya120111 approved these changes

2024-04-10 20:10 UTC, merged